name: Ruby

on:
  push:
    branches:
      - main

  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    name: Ruby ${{ matrix.ruby }}
    strategy:
      fail-fast: false
      matrix:
        rails_version: ['5.2.6', '6.0.4.4', '6.1.4.4', '7.0.2.3', 'main']
        ruby_version: ['2.5', '2.6', '2.7', '3.0', '3.1']
        exclude:
          - rails_version: '5.2.6'
            ruby_version: '3.0'
          - rails_version: '5.2.6'
            ruby_version: '3.1'
          - rails_version: '6.0.4.4'
            ruby_version: '3.0'
          - rails_version: '6.0.4.4'
            ruby_version: '3.1'
          - rails_version: '7.0.2.3'
            ruby_version: '2.5'
          - rails_version: '7.0.2.3'
            ruby_version: '2.6'
          - rails_version: 'main'
            ruby_version: '2.5'
          - rails_version: 'main'
            ruby_version: '2.6'

    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby_version }}
        bundler-cache: true
    - uses: actions/cache@v2
      with:
        path: vendor/bundle
        key: gems-build-rails-${{ matrix.rails_version }}-ruby-${{ matrix.ruby_version }}-${{ hashFiles('**/Gemfile.lock') }}
    - name: Run the default task
      run: |
        bundle config path vendor/bundle
        bundle update
        bundle exec rake
      env:
        RAILS_VERSION: ${{ matrix.rails_version }}
